### ISSUE TITLE
AMD gpu?

### ISSUE THREAD

**Issue by ektorcaba** [masterofobzene/FileConverter-H265#3]
Hi, can add Amd GPU support? thanks!

**Comment by masterofobzene** [comment]
I'm not familiar with AMD since I have an Nvidia card, don't know if AMD cards have dedicated chips to process video encoding like Nvidia cards do. If anyone here has AMD cards and knowledge it would be good if they could fork it and make it compatible. 

This is out of my skills and knowledge, sorry.
